services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookshop_net
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    image: omar968/projet-django-web:v2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8022:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookshop_net

volumes:
  db_data:

networks:
  bookshop_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.122.0.0/16