# Generated by Django 5.2.1 on 2026-06-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
