# Generated by Django 5.2.1 on 2026-06-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_internal_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='internal_notes',
        ),
    ]
